image: python:latest
before_script:
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install trcli
build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - python --version
    - pip --version
    - trcli
    - script:
  - "curl -X POST --fail -F token=glptt-568af68eaee864b4b14ead136e55413c8efdcdf3 -F ref=REF_NAME https://gitlab.com/api/v4/projects/41367989/trigger/pipeline"
test-job1:
  stage: test
  script:
    - echo "This job tests something"
    - echo "This job tests something"
    - trcli
    - trcli -y \
      -h "http://127.0.0.1:7777/testrail" \
      -u "ssalmanburhan@gmail.com" \
      -p "salmanali03463816762" \
      --project "markdown Test" \
      parse_junit \
      --title "Automated test" \
      -f "ci_test.xml"

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
