build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-job1:
  stage: test
  script:
    - echo "This job tests something"
    -trcli \
      -h "http://127.0.0.1:7777/testrail" \
      -u "ssalmanburhan@gmail.com" \
      -p "salmanali03463816762" \
      --project "markdown Test" \
      parse_junit \
      --title "Automated test" \
      -f "ci_test.xml"

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
